version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: user_management_postgres
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d myappdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  fastapi:
    build: .
    container_name: user_management_fastapi
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app  # Set Python path to include the app directory
      - DATABASE_URL=postgresql://user:password@postgres:5432/myappdb
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: user_management_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
